### ISSUE TITLE
Itegra - Feedback

### ISSUE THREAD

**Issue by MatheusDaeuble** [MardonioEng/itegraflix#1]
Bom dia Mardonio, obrigado por participar do nosso desafio!

Me chamo Matheus e serei o responsável por analisar seu desafio. Segue meu breve Feedback sobre seu projeto, considere tudo como sugestões, se discordar de algo ou ficar com alguma dúvida estou disponível para discutirmos sobre.

**Review Geral:**

- Readme muito bom, explicativo e bem estruturado!
- Ponto extra por usar typescript, mas deixou a desejar na "tipagem", ví que você usou o tipo `any` em diversos locais, limitando as vantagens de utilizar esse superset.
- Design muito semelhante ao proposto, parabéns!
- Boa utilização de feedbacks de loading.
- Cabeçalho deveria ficar fixo na parte superior.
- Aplicação responsiva, parabéns!
- Boa organização de pastas, mas poderia ter realizado a configuração da api em uma pasta/arquivo especifico.
- Boa componentização e uso dos React Hooks.
- Boa divisão de commits!
- Bom uso de animações!
- No seu package.json estão declarados alguns pacotes que não estão sendo utilizados (ex: loading-animations-react). Esses pacotes não utilizados aumentam desnecessariamente o bundle da sua aplicação.
- Gostei do uso do arquivo p/ variáveis de ambiente (.env). 

**Dicas:**
- Você poderia ter limitado de alguma forma o tamanho das imagens de cartaz, em alguns casos (monitores ultrawide por exemplo), essas imagens ficaram demasiadamente grandes.
- Lembre-se de adicionar `background-color` na tag `html`, isso evitará que apareça um fundo branco caso o usuário tente realizar scroll no inicio/fim da tela (em dispositivos móveis).

Mardonio, novamente obrigado por participar do nosso desafio. Foi um prazer poder avaliar seu código, espero que encare as observações como algo construtivo, qualquer dúvida/questionamento entre em contato. Em breve entrarão em contato com você para te dar um feedback sobre sua participação em nosso processo seletivo.

**Comment by MardonioEng** [comment]
Bom dia, Mateus!

Muito obrigado pelo feedback. Essas observações claramente são construtivas.

Novamente, muito obrigado!
